language: cpp
cache: ccache
sudo: false

addons:
  apt:
    sources: &zeromq_source
    - sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_14.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_14.04/Release.key'
    sources: &toolchain
    - ubuntu-toolchain-r-test
    packages: &required_packages
      - cmake
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-regex-dev
      - libboost-test-dev
      - libboost-thread-dev
      - libxml2-dev
      - libpcap-dev
      - libsystemd-journal-dev
      - libsctp-dev
    packages: &optional_packages
      - libssl-dev
      - libczmq-dev

matrix:
  include:
    - compiler: gcc
      sudo: true
      before_install:
        - sudo apt-get remove -qq libssl-dev
      env: DTLS="OFF" ZMQ="OFF"
      addons:
        apt:
          packages:
            - *required_packages
    - compiler: clang
      sudo: true
      before_install:
        - sudo apt-get remove -qq libssl-dev
      env: DTLS="OFF" ZMQ="OFF"
      addons:
        apt:
          packages:
            - *required_packages
    - compiler: gcc
      env: DTLS="ON" ZMQ="ON"
      addons:
        apt:
          sources: *zeromq_source
          packages:
            - *required_packages
            - *optional_packages
    - compiler: clang
      env: DTLS="ON" ZMQ="ON"
      addons:
        apt:
          sources: *zeromq_source
          packages:
            - *required_packages
            - *optional_packages
    - compiler: gcc
      env: DTLS="ON" ZMQ="OFF" MATRIX_EVAL="CC=gcc-5 CXX=g++-5"
      addons:
        apt:
          sources: *toolchain
          packages:
            - *required_packages
            - g++-5
    - compiler: gcc
      env: DTLS="ON" ZMQ="OFF" MATRIX_EVAL="CC=gcc-6 CXX=g++-6"
      addons:
        apt:
          sources: *toolchain
          packages:
            - *required_packages
            - g++-6
    - compiler: gcc
      env: DTLS="ON" ZMQ="OFF" MATRIX_EVAL="CC=gcc-7 CXX=g++-7"
      addons:
        apt:
          sources: *toolchain
          packages:
            - *required_packages
            - g++-7
    - compiler: gcc
      env: DTLS="ON" ZMQ="ON" MATRIX_EVAL="CC=gcc-7 CXX=g++-7"
      addons:
        apt:
          sources:
          - *toolchain
          - *zeromq_source
          packages:
            - *required_packages
            - *optional_packages
            - g++-7

before_install:
  - eval "${MATRIX_EVAL}"

script: cmake -DCMAKE_INSTALL_PREFIX=/tmp -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSUPPORT_JOURNALD=ON -DSUPPORT_DTLS="$DTLS" -DSUPPORT_ZMQ="$ZMQ" . && make && make test && make install
